name: Deploy to GitHub Pages

on:
  push:
    branches:
      - end0 # Replace with your branch name if different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16 # Use the Node.js version that suits your project

    - name: Install dependencies and build
      run: |
        npm ci
        npm run build:gh-pages

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build # The build output directory for your React app
